apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: rabbitmq
        image: rabbitmq:management
        ports:
          - containerPort: 15672
            name: http-rabbitmq
          - containerPort: 5672
            name: queue
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: {{ .Values.rabbitmq.user }}
          - name: RABBITMQ_DEFAULT_PASS
            value: {{ .Values.rabbitmq.password }}
          