apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: polybase-vue
            port:
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: polybase-vue
            port:
              number: 80
      - pathType: Prefix
        path: "/models"
        backend:
          service:
            name: polybase-vue
            port:
              number: 80
      - pathType: Prefix
        path: "/textures"
        backend:
          service:
            name: polybase-vue
            port:
              number: 80