apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.service.frontend.name }}
            port:
              number: {{ .Values.service.frontend.port }}
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.port }}
      - pathType: Prefix
        path: "/models"
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.port }}
      - pathType: Prefix
        path: "/textures"
        backend:
          service:
            name: {{ .Values.service.backend.name }}
            port:
              number: {{ .Values.service.backend.port }}