deployment:
  name: polybase-fe

app:
  name: polybase-fe

image:
  name: localhost:5000/polybase-fe
  port: 80
  version: latest

service:
  frontend:
    name: polybase-fe
    port: 80
  backend:
    name: polybase-be
    port: 8080