kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 3d-model-shop
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://registry:5000"]
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker